name: poetry-setup
description: Install and cache poetry and dependencies

inputs:
  os:
    required: true
    description: OS to use in the cache key

  python_exe:
    required: true
    default: python
    description: Name of the python executable to use when installing poetry

  poetry_version:
    required: true
    default: latest
    description: Poetry version to install

runs:
  using: composite
  steps:
    - name: Get python version
      id: get-py-version
      shell: pwsh
      run: |
        $py_version = Invoke-Expression "${{ inputs.python_exe }} -c `"print(__import__('platform').python_version())`""
        Write-Output "::set-output name=py_version::$py_version"

    - name: Get latest poetry version
      id: get-poetry-version
      shell: pwsh
      run: |
        $poetry_version = "${{ inputs.poetry_version }}"
        if ($poetry_version -eq "latest"){
          $poetry_version = (gh api repos/python-poetry/poetry/releases/latest | ConvertFrom-Json).tag_name
        }
        Write-Output "::set-output name=poetry_version::$poetry_version"

    - name: Cache Poetry
      id: cache-poetry
      uses: actions/cache@v3
      with:
        path: .installed-poetry
        key: poetry-${{ steps.get-poetry-version.outputs.poetry_version }}-${{ inputs.os }}-py${{ steps.get-py-version.outputs.py_version }}
    
    - name: Install poetry
      shell: pwsh
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ${{ github.workspace }}/.github/actions/poetry/script.ps1  `
          -installed_path .installed-poetry `
          -version_to_install ${{ steps.get-poetry-version.outputs.poetry_version }} `
          -python_exe ${{ inputs.python_exe }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: .virtualenvs
        key: deps-poetry-${{ steps.get-poetry-version.outputs.poetry_version }}-${{ inputs.os }}-py${{ steps.get-py-version.outputs.py_version }}-${{ hashFiles('**/poetry.lock') }}
        